name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  rename-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          pip show pyyaml
      - name: Run rename script
        run: python Script/rename_md_files.py
      - name: Commit changes
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add .
          git commit -m "Renamed Markdown files, updated titles and cleaned image links" || echo "No changes to commit"
          git push

  update-csv:
    runs-on: ubuntu-latest
    needs: rename-files
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dateutil
          pip show pyyaml
          pip show python-dateutil
      - name: Run update blog CSV script
        run: python Script/update_blog_csv.py
      - name: Check Git status
        run: git status
      - name: Pull remote changes
        run: git pull --rebase
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add Table/Archive\ of\ 涂俊杰JunJie\ blog.csv
          git commit -m "Update blog CSV" || echo "No changes to commit"
          git push
