name: Update Blog CSV

on:
  push:
    paths:
      - '*.md'  # 检测根目录下的 .md 文件变化

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      # 检出仓库代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 设置 Python 环境
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 安装依赖（PyYAML 和 python-dateutil）
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml python-dateutil

      # 运行脚本更新 CSV（从 Script 目录执行）
      - name: Run script to update CSV
        run: python Script/update_blog_csv.py
        working-directory: ${{ github.workspace }}

      # 提交更改
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add "Table/Archive of 涂俊杰JunJie blog.csv"
          git commit -m "Update blog CSV with new articles" || echo "No changes to commit"
          git push
        working-directory: ${{ github.workspace }}
