name: Update Blog CSV

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-csv:
    runs-on: ubuntu-latest
    needs: rename-files  # 确保在 rename-files 完成后执行
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Run update blog CSV script
        run: python Script/update_blog_csv.py
      - name: Commit changes
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add .
          git commit -m "Update blog CSV" || echo "No changes to commit"
          git push
